---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-mysqlbak-web
  namespace: mysqlbak
  resourceVersion: '92027938'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gin-mysqlbak-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gin-mysqlbak-web
    spec:
      containers:
        - image: 'harbor-tj.ts-it.cn:63333/mysqlbak/gin-mysqlbak-web:2.0.2-SP3'
          imagePullPolicy: IfNotPresent
          name: mysql-pod
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-conf
              subPath: default.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: mysqlbak-web-conf
          name: nginx-conf

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gin-mysqlbak-web
  name: gin-mysqlbak-web
  namespace: mysqlbak
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 19008
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: gin-mysqlbak-web
  sessionAffinity: None
  type: NodePort

