apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-mysqlbak-web
  namespace: mysqlbak
spec:
  selector:
    matchLabels:
      app: gin-mysqlbak-web
  replicas: 1
  template:
    metadata:
      labels:
        app: gin-mysqlbak-web
    spec:
      containers:
      - name: mysql-pod
        imagePullPolicy: IfNotPresent
        image: chenteng/gin-mysqlbak-web:1.1.7
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: mysqlbak-web-conf 
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysqlbak
  labels:
    app: gin-mysqlbak-web
spec:
  type: NodePort
  ports:
  - targetPort: 80
    nodePort: 32080
    port: 80
  selector:
     app: gin-mysqlbak-web		  
