---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-mysqlbak-server
  namespace: mysqlbak
  resourceVersion: '92029093'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gin-mysqlbak-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gin-mysqlbak-server
    spec:
      containers:
        - image: 'harbor-tj.ts-it.cn:63333/mysqlbak/gin-mysqlbak-server:2.0.4'
          imagePullPolicy: IfNotPresent
          name: gin-mysqlbak-server
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/conf/dev/base.toml
              name: baseconf
              subPath: base.toml
            - mountPath: /app/conf/dev/mysql_map.toml
              name: mysqlconf
              subPath: mysql_map.toml
            - mountPath: /app/conf/config.ini
              name: iniconf
              subPath: config.ini
            - mountPath: /app/bakfile
              name: mysqlbak-data
              subPath: mysql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /data/gin-mysqlbak
            type: DirectoryOrCreate
          name: mysqlbak-data
        - configMap:
            defaultMode: 420
            name: mysqlbak-base-conf
          name: baseconf
        - configMap:
            defaultMode: 420
            name: mysqlbak-mysql-conf
          name: mysqlconf
        - configMap:
            defaultMode: 420
            name: mysqlbak-ini-conf
          name: iniconf

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gin-mysqlbak-server
  name: gin-mysqlbak-server
  namespace: mysqlbak
spec:
  externalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 19009   ## server端地址
      port: 8880
      protocol: TCP
      targetPort: 8880
  selector:
    app: gin-mysqlbak-server
  sessionAffinity: None
  type: NodePort
