apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlbak-mysql-conf
  namespace: mysqlbak
data:
  mysql_map.toml: |
    [list]
        [list.default]
            driver_name = "mysql"
            data_source_name = "root:1qaz@WSX@tcp(127.0.0.1:3306)/gin-mysqlbak?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
            max_open_conn = 20
            max_idle_conn = 10
            max_conn_life_time = 100
