---
apiVersion: v1
data:
  config.ini: >
    [base]
    debug_mode="debug"
    time_location="Asia/Chongqing"
    download_url="http://10.20.110.51:19009"   ## 用于下载备份文件使用，需要与server端svc开放的地址端口相同
    [http]
    addr = ":8880"                       # 监听地址, default ":8700"
    read_timeout = 10                   # 读取超时时长
    write_timeout = 10                  # 写入超时时长
    max_header_bytes = 20               # 最大的header大小，二进制位长度
    [HostLostAlarms]
    enable = true  ## 是否启动主机检测 
    accessToken = "77f579efbefeefc316b55d3caea1ba1963db2f1319aa7520cbfd9626de073fdc"  ## 主机检测钉钉报警配置
    secret = "SEC72586e3f7ff6db4b2ad24eac905f308a9ddb0b1b9809af31e5623a14abb424b2"
    [dingProxyAgent]
    enable = false    ## 用于无外网环境下发送钉钉消息
    addr = 127.0.0.1:39999
    title = "公司测试环境备份平台"
    content = "公司测试环境备份平台"
    [swagger]
    title="gin-mysqlbak swagger API"
    desc="This is a sample server celler server."
    host="127.0.0.1:8880"
    base_path=""
    [jaeger]
    enable = false
    addr = 127.0.0.1:6831
    [mysql]
    host = 127.0.0.1
    port = 3306
    user = root
    password = chenteng
    dbname = gin-mysqlbak
    [app] ## 应用相关配置
    mysqlAvatar: http://qiniu.yunxue521.top/mysql.jpeg
    elasticAvatar: http://qiniu.yunxue521.top/elastic.jpg
    [cluster]
    ## 集群任务同步周期(分钟)
    clusterSyncPeriod = "*/1 * * * *"
kind: ConfigMap
metadata:
  annotations: {}
  name: mysqlbak-ini-conf
  namespace: mysqlbak

