---
apiVersion: v1
data:
  base.toml: |
    [log]
        log_level = "trace"         #日志打印最低级别
        [log.file_writer]           #文件写入配置
            on = true
            log_path = "./logs/gin-mysqlbak.inf.log"
            rotate_log_path = "./logs/gin-mysqlbak.inf.log.%Y%M%D%H"
            wf_log_path = "./logs/gin-mysqlbak.wf.log"
            rotate_wf_log_path = "./logs/gin-mysqlbak.wf.log.%Y%M%D%H"
        [log.console_writer]        #工作台输出
            on = false
            color = false
kind: ConfigMap
metadata:
  name: mysqlbak-base-conf
  namespace: mysqlbak
  resourceVersion: '90333491'

