apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlbak-web-conf
  namespace: mysqlbak
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html =404;
        }
    
          location ^~/prod-api/ {
            proxy_pass http://gin-mysqlbak-server:8880/;
        }
          location ^~/public/download/ {
            proxy_pass http://gin-mysqlbak-server:8880/;
        }
    
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

